CREATE USER 'roro12@localhost' IDENTIFIED BY 'Rolo12lo'  ; -- CREAR USER CON DOMINIO Y PASSWORD

GRANT SELECT ON sql_coder.* TO 'roro12@localhost' ; -- OTORGAR PERMISOS DE LECTURA 

SHOW GRANTS FOR 'roro12@localhost' ; -- MOSTRAR PERMISOS ESTABLECIDOS AL USUARIO




CREATE USER 'luc.ag@192.168.100.7' IDENTIFIED BY 'Chasco2332'  ; -- CREAR USER CON DOMINIO Y PASSWORD

GRANT SELECT, INSERT, UPDATE ON sql_coder.* TO 'luc.ag@192.168.100.7' ; -- OTORGAR PERMISOS DE LECTURA, INSERCION Y MODIFICACION

SHOW GRANTS FOR 'luc.ag@192.168.100.7' ; -- MOSTRAR PERMISOS ESTABLECIDOS AL USUARIO